import { test, expect } from '@playwright/test';
import { accessRow, applyDecisions, assertProductLanguage, confirmCompletion, decideAll, downloadAudit, expandConnected, expectFullyInViewport, nav, openSarahEvent, provision } from '../helpers/iga-flow.js';
import { assertLogoConsistency, verifyLogoCatalog } from '../helpers/application-logos.js';

const sarahRow = page => page.locator('[data-record-id="WD-MOV-2026-0842"]');
const stepper = page => page.getByLabel('Access lifecycle', { exact: true });

test('Sarah workflow has clean source information, ServiceNow decisions, scoped navigation and persistent operational resume', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/');
  await nav(page, 'Applications');
  const logoSources = await verifyLogoCatalog(page);
  await nav(page, 'Overview');
  await assertLogoConsistency(page, logoSources);
  await expect(stepper(page)).toHaveCount(0);
  await expect(page.locator('.access-panel')).toContainText('Employee Self Service');
  await expect(page.locator('.access-panel')).not.toContainText('Finance Request Approver');
  await nav(page, 'Lifecycle events');
  await expect(stepper(page)).toHaveCount(0);
  await openSarahEvent(page);
  await assertLogoConsistency(page, logoSources);
  await expect(stepper(page)).toBeVisible();
  const source = page.locator('.event-source-label');
  await expect(source).toContainText('Workday mover event');
  expect(await source.evaluate(element => {
    const boxes = [...element.children].map(child => child.getBoundingClientRect());
    return Math.max(...boxes.map(box => box.top)) - Math.min(...boxes.map(box => box.top)) < 12;
  })).toBe(true);
  expect(await source.evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(15);
  await page.getByRole('button', { name: 'Review access recommendations', exact: true }).click();
  await expect(stepper(page)).toBeVisible();
  await expect(page.getByRole('button', { name: 'Accept all recommendations', exact: true })).toHaveClass(/primary/);
  await expect(page.getByRole('button', { name: 'Apply decisions', exact: true })).toHaveClass(/secondary/);
  await expect(accessRow(page, 'h-snow-self')).toContainText('Employee Self Service');
  await expect(accessRow(page, 'h-snow-self')).toContainText('Keep');
  await expect(accessRow(page, 'h-snow-approver')).toContainText('Finance Request Approver');
  await expect(accessRow(page, 'h-snow-approver')).toContainText('Grant');
  await assertLogoConsistency(page, logoSources);
  await decideAll(page);
  await assertLogoConsistency(page, logoSources);
  await applyDecisions(page);
  await expect(stepper(page)).toBeVisible();
  await provision(page);
  await expect(page.getByRole('button', { name: 'Completed', exact: true })).toHaveCount(0);
  await expandConnected(page);
  await expect(accessRow(page, 'h-snow-approver')).toContainText('Granted');
  await page.getByLabel('Show unchanged access').check();
  await expect(accessRow(page, 'h-snow-self')).toContainText('Retained');
  await assertLogoConsistency(page, logoSources);
  await expect(page.getByRole('button', { name: 'Return to lifecycle events', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'View audit trail', exact: true })).toHaveClass(/primary/);
  await page.getByRole('button', { name: 'View audit trail', exact: true }).click();
  await expect(stepper(page)).toBeVisible();
  await expect(page.getByRole('button', { name: 'Return to lifecycle events', exact: true })).toHaveClass(/primary/);
  await expect(page.getByRole('button', { name: 'Export audit trail', exact: true })).toHaveClass(/secondary/);
  await expect(page.locator('.audit-actions .button')).toHaveText(['Return to lifecycle events', 'Export audit trail']);
  await expect(page.locator('.notice')).toContainText('1 manual task open.');
  await expect(page.locator('.evidence-panel tbody tr')).toHaveCount(16);
  await assertLogoConsistency(page, logoSources);
  await page.getByRole('button', { name: 'Return to lifecycle events', exact: true }).click();
  await expect(stepper(page)).toHaveCount(0);
  await expect(sarahRow(page)).toContainText('Manual task open');
  await sarahRow(page).getByRole('button').first().click();
  await expect(page.getByRole('heading', { name: 'Provisioning', exact: true })).toBeVisible();
  await expect(page.locator('.legacy-panel')).toHaveClass(/task-attention/);
  await expectFullyInViewport(page, page.locator('.legacy-panel'));
  for (const text of ['Legacy Finance DB', 'SN-TASK-004812', 'Martin Keller', 'Monday 19 October · 12:00 UTC', 'Task open']) await expect(page.locator('.legacy-panel')).toContainText(text);
  await page.reload();
  await nav(page, 'Lifecycle events');
  await expect(sarahRow(page)).toContainText('Manual task open');
  await sarahRow(page).getByRole('button').first().click();
  await expect(page.getByRole('heading', { name: 'Provisioning', exact: true })).toBeVisible();
  await expectFullyInViewport(page, page.locator('.legacy-panel'));
  await confirmCompletion(page);
  await expect(page.locator('.legacy-panel .badge')).toHaveText('Completed');
  await expect(page.locator('.legacy-panel')).not.toHaveClass(/task-attention/);
  await page.getByRole('button', { name: 'View audit trail', exact: true }).click();
  await expect(stepper(page)).toBeVisible();
  await expect(page.getByRole('button', { name: 'All (16)', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('.evidence-panel tbody tr')).toHaveCount(16);
  await expect(accessRow(page, 'h-snow-self')).toContainText('Keep');
  await expect(accessRow(page, 'h-snow-approver')).toContainText('Grant');
  await page.getByLabel('Show full history').check();
  await expect(page.getByRole('table', { name: 'Lifecycle history' })).toContainText('Completed');
  const bundle = await downloadAudit(page);
  expect(bundle.legacyTask.status).toBe('Completed');
  expect(bundle.lifecycleEvidence).toHaveLength(1);
  expect(bundle.accessDecisions).toHaveLength(16);
  await nav(page, 'Audit trail');
  await expect(stepper(page)).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Return to lifecycle events', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Export audit trail', exact: true })).toHaveClass(/secondary/);
  await page.reload();
  await nav(page, 'Lifecycle events');
  await expect(sarahRow(page)).toContainText('Completed');
  await sarahRow(page).getByRole('button').first().click();
  await expect(page.getByRole('heading', { name: 'Audit trail', exact: true })).toBeVisible();
  await expect(stepper(page)).toBeVisible();
  await page.getByRole('button', { name: 'Return to lifecycle events', exact: true }).click();
  await expect(sarahRow(page)).toContainText('Completed');
  await sarahRow(page).getByRole('button').first().click();
  await expect(page.getByRole('heading', { name: 'Audit trail', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Confirm completion', exact: true })).toHaveCount(0);
  await page.keyboard.press('Shift+G');
  await expect(page.getByRole('dialog', { name: '10-minute guide', exact: true })).toBeVisible();
  await page.keyboard.press('Shift+R');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  expect(await page.evaluate(() => scrollY)).toBe(0);
  await expect(stepper(page)).toHaveCount(0);
  await expect(page.locator('.access-panel tbody tr')).toHaveCount(5);
  await expect(page.locator('.access-panel')).not.toContainText('Finance Request Approver');
  await assertProductLanguage(page);
});

test('workflow Audit Trail scopes its actions before evaluation and fits a narrow viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await openSarahEvent(page);
  await page.getByRole('button', { name: 'Step 5: Audit trail', exact: true }).click();
  await expect(stepper(page)).toBeVisible();
  await expect(page.getByRole('heading', { name: 'No access decisions', exact: true })).toBeVisible();
  for (const [label, variant] of [['Return to lifecycle events', 'primary'], ['Export audit trail', 'secondary']]) {
    const action = page.getByRole('button', { name: label, exact: true });
    await expect(action).toHaveClass(new RegExp(variant));
    expect(await action.evaluate(element => {
      const rect = element.getBoundingClientRect();
      return rect.left >= 0 && rect.right <= innerWidth;
    })).toBe(true);
  }
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await nav(page, 'Audit trail');
  await expect(stepper(page)).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Return to lifecycle events', exact: true })).toHaveCount(0);
  await expect(page.locator('.workspace-records tbody tr')).toHaveCount(5);
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('northstar-identity-demo-v1')));
  expect(stored.evaluated).toBe(false);
});

test('audit policy drawers show relevant rules and preserve filter, history, records and scroll', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/');
  await openSarahEvent(page);
  await page.getByRole('button', { name: 'Review access recommendations', exact: true }).click();
  await decideAll(page);
  await nav(page, 'Audit trail');
  await expect(stepper(page)).toHaveCount(0);
  await expect(page.locator('.evidence-panel tbody tr')).toHaveCount(16);
  await page.getByRole('button', { name: 'Policy-locked', exact: true }).click();
  await page.getByLabel('Show full history').check();
  const policy = accessRow(page, 'a-payment').getByRole('button', { name: 'View policy POL-AI-303', exact: true });
  await policy.evaluate(element => element.scrollIntoView({ block: 'center' }));
  const scroll = await page.evaluate(() => scrollY);
  const saved = await page.evaluate(() => localStorage.getItem('northstar-identity-demo-v1'));
  await policy.click();
  const drawer = page.getByRole('dialog', { name: 'Human-only payment control' });
  await expect(drawer).toContainText('POL-AI-303');
  await expect(drawer).toContainText('Payment approval is restricted to human identities and cannot be overridden for an AI agent.');
  await expect(drawer).toContainText('Not permitted by policy');
  await expect(drawer.locator('input, textarea, select')).toHaveCount(0);
  await assertProductLanguage(page);
  await page.keyboard.press('Escape');
  await expect(policy).toBeFocused();
  expect(await page.evaluate(() => scrollY)).toBe(scroll);
  expect(await page.evaluate(() => localStorage.getItem('northstar-identity-demo-v1'))).toBe(saved);
  await expect(page.getByRole('button', { name: 'Policy-locked', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Show full history')).toBeChecked();
  await expect(page.getByRole('tab', { name: 'Decisions', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(page.locator('.evidence-panel tbody tr')).toHaveCount(1);
  await page.getByLabel('Show full history').uncheck();
  await page.getByRole('button', { name: 'All (16)', exact: true }).click();
  await accessRow(page, 'h-payment').getByRole('button', { name: 'View policy POL-SOD-017', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('Approved with condition');
  await expect(page.getByRole('dialog')).toContainText('Remove receivables access before activating payment approval');
  await page.getByRole('button', { name: 'Close details', exact: true }).click();
  await expect(page.locator('.evidence-panel tbody tr')).toHaveCount(16);
  const policies = page.locator('.evidence-panel .policy-link');
  expect(await policies.count()).toBe(17);
  await accessRow(page, 'a-payment').getByRole('button', { name: 'View policy POL-AI-303', exact: true }).click();
  await page.keyboard.press('Shift+R');
  await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  expect(await page.evaluate(() => scrollY)).toBe(0);
});
