import React, { useCallback, useState } from 'react';
import { ArrowRight, CheckCircle2, ChevronRight, ClipboardCheck, Download, FileCheck2, Fingerprint, History, ShieldCheck } from 'lucide-react';
import { decisions, resourceName, subjectName } from '../data/catalog.js';
import { controlComplete, readiness } from '../demo/state.js';
import { Badge, Button, Drawer, Empty, Field, Notice, PageTitle, SectionTitle, formatTime } from '../components/UI.jsx';

const byId = Object.fromEntries(decisions.map(d => [d.id, d]));
function latest(records) {
  const grouped = new Map();
  records.forEach(record => grouped.set(record.rowId, record));
  return [...grouped.values()];
}
export default function Evidence({ state, navigate }) {
  const [tab, setTab] = useState('decision');
  const [history, setHistory] = useState(false);
  const [detail, setDetail] = useState(null);
  const close = useCallback(() => setDetail(null), []);
  const decisionRows = history ? state.decisionEvidence : latest(state.decisionEvidence);
  const fulfillmentRows = history ? state.fulfillmentEvidence : latest(state.fulfillmentEvidence);
  const records = tab === 'decision' ? decisionRows : fulfillmentRows;
  const outstanding = !controlComplete(state) || state.review === 'pending' || state.tasks['h-payment']?.status === 'Ready to execute';
  const completedLegacy = state.fulfillmentEvidence.find(e => e.rowId === 'h-legacy' && e.status === 'Removed');
  const completionRef = row => row.status === 'Task open' ? 'Pending completion' : row.status === 'Not granted' ? 'No grant executed' : row.reference;
  function exportEvidence() {
    const enrich = record => ({ ...record, subject: subjectName(byId[record.rowId]), resource: resourceName(byId[record.rowId]), scope: byId[record.rowId].scope, ...(record.rowId === 'h-payment' ? { additionalPolicy: 'POL-SOD-017' } : {}) });
    const bundle = { product: 'Northstar Identity', syntheticDemo: true, customer: 'Meridian Global', eventId: 'WD-MOV-2026-0842', source: 'Workday', previousRole: 'Finance Analyst', targetRole: 'Finance Manager', effectiveDate: '2026-10-12', timezone: 'UTC', decisionEvidence: state.decisionEvidence.map(enrich), fulfillmentEvidence: state.fulfillmentEvidence.map(enrich), outcomes: { coreRoleReady: readiness(state), obsoleteAccessRemoved: controlComplete(state), paymentReview: state.review, allControlsResolved: !outstanding } };
    const url = URL.createObjectURL(new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' }));
    const a = document.createElement('a'); a.href = url; a.download = 'northstar-sarah-miller-evidence.json'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  if (!state.evaluated) return <><PageTitle eyebrow="AUDIT & ASSURANCE" title="A decision trail. An execution trail." description="Know why access should change—and prove whether it did." /><Empty title="No evidence recorded yet" onAction={() => navigate(1)}>Evaluate the Workday event to create decision evidence. Fulfillment evidence is recorded separately when the changes are executed.</Empty></>;
  return <>
    <PageTitle eyebrow="AUDIT & ASSURANCE · WD-MOV-2026-0842" title="Explain the decision. Prove the control." description="Two distinct evidence trails, linked to the same business event." action={<Button variant="secondary" icon={Download} onClick={exportEvidence}>Export evidence</Button>} />
    <div className="evidence-intro-grid"><section className={`evidence-definition ${tab === 'decision' ? 'selected' : ''}`}><span className="definition-icon"><Fingerprint size={24} strokeWidth={1.5} /></span><div><span className="eyebrow">01 · DECISION EVIDENCE</span><h2>Why should access change?</h2><p>Who · What · Why · Policy · Timestamp · Decision</p><small>Records the access determination and any human approval.</small></div></section><section className={`evidence-definition ${tab === 'fulfillment' ? 'selected' : ''}`}><span className="definition-icon"><ClipboardCheck size={24} strokeWidth={1.5} /></span><div><span className="eyebrow">02 · FULFILLMENT EVIDENCE</span><h2>Did the change actually happen?</h2><p>How · Status · Owner · SLA · Completion reference</p><small>Records execution and exposes controls that remain open.</small></div></section></div>
    {outstanding && <Notice tone="amber"><strong>Evidence does not yet prove all controls complete.</strong> {!state.fulfillmentStarted ? 'The decisions are recorded, but effective-date fulfillment has not run.' : !controlComplete(state) ? 'The legacy task remains open: Sarah’s direct and agent-mediated DB write access has not yet been proven removed.' : state.review === 'pending' ? 'Payment approval remains awaiting a human decision.' : 'The approved payment permission is awaiting execution.'} <button className="inline-link" onClick={() => navigate(!state.fulfillmentStarted || !controlComplete(state) || state.tasks['h-payment']?.status === 'Ready to execute' ? 3 : 2)}>Resolve outstanding control</button></Notice>}
    <div className="evidence-toolbar"><div className="tabs" role="tablist" aria-label="Evidence type"><button role="tab" aria-selected={tab === 'decision'} className={tab === 'decision' ? 'active' : ''} onClick={() => setTab('decision')}><Fingerprint size={16} />Decision evidence<span>{latest(state.decisionEvidence).length}</span></button><button role="tab" aria-selected={tab === 'fulfillment'} className={tab === 'fulfillment' ? 'active' : ''} onClick={() => setTab('fulfillment')}><ClipboardCheck size={16} />Fulfillment evidence<span>{latest(state.fulfillmentEvidence).length}</span></button></div><label className="history-toggle"><input type="checkbox" checked={history} onChange={e => setHistory(e.target.checked)} /><History size={15} />Show full history</label></div>
    <section className="panel evidence-panel"><SectionTitle title={tab === 'decision' ? 'Decision evidence' : 'Fulfillment evidence'} description={history ? 'Every recorded transition, including earlier review and open-task states.' : 'Latest recorded state for each access determination.'}><span className="muted-label">{records.length} records</span></SectionTitle>
      {records.length ? <table><thead><tr>{(tab === 'decision' ? ['Who / what', 'Decision', 'Why / policy', 'Decision timestamp', ''] : ['What changed', 'How / owner', 'Execution status', 'SLA / due', 'Completion reference', '']).map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{records.map(record => {
        const row = byId[record.rowId];
        return <tr key={record.id}><td><button className="table-link" onClick={() => setDetail({ type: tab, record })}>{resourceName(row)}</button><small className="cell-subtitle">{row.scope === 'outbound' ? 'Agent on behalf of Sarah Miller' : 'Sarah Miller'} · {row.scope}</small></td>
          {tab === 'decision' ? <><td><Badge>{record.decision}</Badge></td><td className="reason-cell">{record.why}<small className="cell-subtitle policy-id">{record.policy}{row.id === 'h-payment' && ' + POL-SOD-017'}</small></td><td className="timestamp-cell">{formatTime(record.timestamp)}<small className="cell-subtitle">{record.actor}</small></td></> : <><td>{record.method}<small className="cell-subtitle">{record.owner}</small></td><td><Badge>{record.status}</Badge></td><td>{record.sla}</td><td className="reference-cell">{completionRef(record)}</td></>}
          <td><button className="icon-button" aria-label={`View ${tab} evidence for ${resourceName(row)} ${record.id}`} onClick={() => setDetail({ type: tab, record })}><ChevronRight size={16} /></button></td></tr>;
      })}</tbody></table> : <div className="table-empty evidence-empty"><ClipboardCheck size={25} /><h3>No fulfillment evidence yet</h3><p>Decisions are recorded. Execution has not started.</p><Button variant="secondary" icon={ArrowRight} onClick={() => navigate(3)}>Open fulfillment</Button></div>}
      <div className="table-footer"><span>Event WD-MOV-2026-0842 · Workday</span><span>UTC timestamps</span></div></section>
    <section className="outcomes-section"><SectionTitle title="Validate the outcomes" description="What this single business event demonstrates—and what remains open." /><div className="outcomes-grid"><Outcome name="Security" stakeholder="Patrick · Identity Governance" complete={controlComplete(state) && state.review !== 'pending' && state.tasks['h-payment']?.status !== 'Ready to execute'} title="Access remains appropriate." text={controlComplete(state) ? 'Obsolete direct and delegated access is removed. Agent payment approval stays blocked. Human payment review is tracked separately.' : 'Decisions are traceable. Residual-access removal is incomplete until both legacy paths have execution evidence.'} /><Outcome name="HR" stakeholder="Tim · HR Operations" complete={readiness(state)} title="Sarah is ready for her new role." text={readiness(state) ? 'Required manager access and the approved AI tool are available from Monday. Additional payment approval is governed separately.' : 'Required manager access is prepared. Effective-date fulfillment must run before productivity readiness is demonstrated.'} /><Outcome name="Architecture" stakeholder="Andre · Enterprise Architecture" complete={state.fulfillmentStarted} title="One governance model." text="The same policy decisions drive API-connected changes and an owned legacy task. Agent permissions use explicit governance boundaries." /></div><p className="outcome-footnote">Mover readiness is measured across Meridian’s transformation. The 95%+ target is a programme outcome, separate from this individual role change.</p></section>
    {detail && <Drawer title={resourceName(byId[detail.record.rowId])} subtitle={detail.type === 'decision' ? 'DECISION EVIDENCE' : 'FULFILLMENT EVIDENCE'} onClose={close}><dl><Field label="Event">WD-MOV-2026-0842 · Workday role change</Field><Field label="Who / subject">{subjectName(byId[detail.record.rowId])}</Field><Field label="What / resource">{resourceName(byId[detail.record.rowId])}</Field>{detail.type === 'decision' ? <><Field label="Decision"><Badge>{detail.record.decision}</Badge></Field><Field label="Why">{detail.record.why}</Field><Field label="Policy">{detail.record.policy}{detail.record.rowId === 'h-payment' && ' + POL-SOD-017'}</Field><Field label="Decision actor">{detail.record.actor}</Field><Field label="Decision timestamp">{formatTime(detail.record.timestamp)}</Field></> : <><Field label="How executed">{detail.record.method}</Field><Field label="Execution status"><Badge>{detail.record.status}</Badge></Field><Field label="Owner">{detail.record.owner}</Field><Field label="SLA / due">{detail.record.sla}</Field>{detail.record.status === 'Task open' && <Field label="Task reference">{detail.record.reference}</Field>}<Field label="Completion reference">{completionRef(detail.record)}</Field><Field label="Execution timestamp">{formatTime(detail.record.timestamp)}</Field>{detail.record.task && <Field label="Linked task">{detail.record.task}</Field>}{detail.record.note && <Field label="Verification note">{detail.record.note}</Field>}</>}</dl><Notice>{detail.type === 'decision' ? 'This record proves an access determination. It does not prove execution. See fulfillment evidence for actual completion.' : detail.record.status === 'Task open' ? 'An open task proves ownership and tracking. It does not prove the access was removed.' : 'Execution evidence is linked to the policy decision and source event.'}</Notice><Button variant="secondary" onClick={() => { setTab(detail.type === 'decision' ? 'fulfillment' : 'decision'); close(); }}>View {detail.type === 'decision' ? 'fulfillment' : 'decision'} evidence</Button></Drawer>}
  </>;
}
function Outcome({ name, stakeholder, complete, title, text }) {
  return <div className="outcome"><div className="outcome-top"><span className="eyebrow">{name.toUpperCase()}</span>{complete ? <CheckCircle2 size={18} className="green-icon" /> : <span className="outcome-pending">Pending</span>}</div><h3>{title}</h3><p>{text}</p><small>{stakeholder}</small></div>;
}
