import React, { useCallback, useRef, useState } from 'react';
import { ArrowRight, Bot, Check, CheckCircle2, Clock3, ClipboardCheck, FileCheck2, Play, Server, ShieldAlert, ShieldCheck, Zap } from 'lucide-react';
import { decisions, resourceName, entitlementById, applicationById } from '../data/catalog.js';
import { REVIEWER, SCENARIO } from '../data/scenario.js';
import { controlComplete, fulfillmentStatus, readiness } from '../demo/state.js';
import { Badge, Button, Drawer, Empty, Field, NextStep, Notice, PageTitle, SectionTitle, Stat } from '../components/UI.jsx';
import { useStepFocus } from '../components/useStepFocus.js';

export default function Fulfillment({ state, dispatch, navigate }) {
  const [taskOpen, setTaskOpen] = useState(false);
  const [reference, setReference] = useState('');
  const [note, setNote] = useState('');
  const [error, setError] = useState('');
  const legacyRef = useRef(null);
  useStepFocus(legacyRef, state.fulfillmentStarted);
  const closeTask = useCallback(() => setTaskOpen(false), []);
  const apiRows = decisions.filter(d => !['KEEP', 'BLOCK'].includes(d.decision) && d.entitlement !== 'legacy-write');
  const completeApi = apiRows.filter(d => ['Granted', 'Removed', 'Not granted'].includes(state.tasks[d.id]?.status)).length;
  const legacyComplete = state.tasks['h-legacy']?.status === 'Removed';
  const canRun = !state.fulfillmentStarted || state.tasks['h-payment']?.status === 'Ready to execute';
  const done = controlComplete(state) && state.review !== 'pending' && state.tasks['h-payment']?.status !== 'Ready to execute';
  if (!state.evaluated) return <><PageTitle eyebrow="CONTROL EXECUTION" title="One decision model. Two execution paths." description="Evaluate the business event before preparing the access changes." /><Empty title="No changes queued yet" onAction={() => navigate(1)}>The Workday evaluation produces the decisions that drive both API execution and controlled legacy tasks.</Empty></>;
  function completeTask(e) {
    e.preventDefault();
    if (!reference.trim() || !note.trim()) { setError('A completion reference and verification note are required.'); return; }
    dispatch({ type: 'COMPLETE_LEGACY', reference, note }); setTaskOpen(false);
  }
  return <>
    <PageTitle eyebrow="CONTROL EXECUTION · SARAH MILLER" title="Consistent governance. Practical fulfillment." description="Automate connected applications. Control legacy changes with ownership, an SLA, and evidence." action={<Button icon={canRun ? Play : ArrowRight} onClick={canRun ? () => dispatch({ type: 'RUN_FULFILLMENT' }) : () => navigate(4)}>{canRun ? state.fulfillmentStarted ? 'Execute approved permission' : 'Run Monday fulfillment' : 'View evidence'}</Button>} />
    <div className={`fulfillment-banner ${done ? 'complete' : ''}`}><div className="banner-icon">{done ? <CheckCircle2 size={26} /> : <Clock3 size={26} />}</div><div><h2>{done ? 'Role access ready. Removal controls complete.' : state.fulfillmentStarted ? legacyComplete ? 'Role access ready. Payment review is outstanding.' : 'Role access ready. Legacy revocation still needs proof.' : `Changes prepared for ${SCENARIO.effectiveDate}.`}</h2><p>{done ? 'Direct and delegated obsolete access has been removed. Payment approval is resolved separately.' : state.fulfillmentStarted ? legacyComplete ? 'Legacy removals are proven. Resolve or execute the additional payment permission to complete the exception.' : 'Required manager access is available. An open legacy task keeps the residual-access control incomplete.' : 'Run the prepared changes for Monday, with policy checks enforced before access is activated.'}</p></div><Badge tone={done ? 'green' : 'amber'}>{done ? 'Controls complete' : state.fulfillmentStarted ? 'Control outstanding' : 'Scheduled'}</Badge></div>
    <div className="stats-row three"><Stat label="Connected access changes" value={`${completeApi} / ${apiRows.length}`} detail={state.review === 'pending' ? 'Payment approval awaits a decision' : 'Removal runs before conflicting grants'} icon={Zap} /><Stat label="Controlled legacy task" value={legacyComplete ? 'Complete' : state.fulfillmentStarted ? '1 open' : '1 queued'} detail="Covers direct and delegated DB write" icon={ClipboardCheck} /><Stat label="Core role readiness" value={readiness(state) ? 'Ready' : 'Prepared'} detail="Payment approval is an additional privilege" icon={ShieldCheck} /></div>
    <section className="panel"><SectionTitle title="Connected applications" description="API fulfillment · Effective-date changes"><Badge tone="blue">Automated execution</Badge></SectionTitle><table><thead><tr><th>Access change</th><th>Subject</th><th>Application</th><th>Action</th><th>Execution status</th></tr></thead><tbody>{apiRows.map(row => <tr key={row.id}><td><strong>{resourceName(row)}</strong></td><td><span className="scope-label">{row.scope === 'human' ? 'Sarah Miller' : <><Bot size={14} />Agent → Sarah context</>}</span></td><td>{applicationById[entitlementById[row.entitlement].app].name}</td><td><Badge>{row.id === 'h-payment' ? state.review === 'approved' ? 'GRANT' : state.review === 'rejected' ? 'DENIED' : 'REVIEW' : row.decision}</Badge></td><td><Badge>{fulfillmentStatus(row, state)}</Badge></td></tr>)}</tbody></table><div className="access-bottom"><ShieldCheck size={16} /><span>SoD control: Accounts Receivable Operator is removed before SAP Payment Approval can be granted.</span></div></section>
    <section className="panel legacy-panel" ref={legacyRef}><SectionTitle title="Legacy Finance DB" description="The same governance decision. A controlled execution path."><Badge tone={legacyComplete ? 'green' : 'amber'}>{legacyComplete ? 'Complete' : state.fulfillmentStarted ? 'Task open' : 'Task queued'}</Badge></SectionTitle><div className="legacy-task"><div className="legacy-task-title"><span className="legacy-icon"><Server size={24} strokeWidth={1.4} /></span><div><span className="eyebrow">SN-TASK-004812 · CONTROLLED MANUAL FULFILLMENT</span><h3>Remove Finance database write access</h3><p>Revoke Sarah’s direct write privilege and the agent’s delegated write permission in her context.</p></div></div><div className="task-details"><div><span>OWNER</span><strong>Martin Keller</strong><small>Finance Platforms</small></div><div><span>SLA / DUE</span><strong>{SCENARIO.legacyDue}</strong><small>4 hours from the effective-date run</small></div><div><span>CONTROL SCOPE</span><strong>Human + agent</strong><small>2 revocations · 1 owned task</small></div><div><span>EVIDENCE</span><strong>{legacyComplete ? 'Completion recorded' : 'Completion not yet proven'}</strong><small>{legacyComplete ? state.fulfillmentEvidence.find(e => e.rowId === 'h-legacy' && e.status === 'Removed').reference : 'DBA verification required'}</small></div></div><div className="task-action"><p>{legacyComplete ? 'The completion reference and verification note are recorded against both access removals.' : 'An approved removal is a decision. The task remains open until execution is evidenced.'}</p><Button variant="secondary" icon={FileCheck2} disabled={!state.fulfillmentStarted || legacyComplete} onClick={() => setTaskOpen(true)}>{legacyComplete ? 'Evidence recorded' : 'Record completion evidence'}</Button></div></div></section>
    <Notice icon={ShieldAlert} tone={state.review === 'pending' ? 'amber' : 'blue'}>{state.review === 'pending' ? <><strong>Payment approval remains unresolved.</strong> Core-role access can proceed, but SAP Payment Approval is withheld until {REVIEWER.name} makes a decision. <button className="inline-link" onClick={() => navigate(2)}>Review exception</button></> : <><strong>The agent’s payment permission stays blocked.</strong> Payment approval is human-only and is never inherited by the agent.</>}</Notice>
    <NextStep label="View evidence" onClick={() => navigate(4)}>Can Meridian prove both why access changed and whether each control actually completed?</NextStep>
    {taskOpen && <Drawer title="Record legacy completion" subtitle="FULFILLMENT EVIDENCE" onClose={closeTask}><Notice>Record the completion reference and verify that both direct and delegated write access are removed.</Notice><dl><Field label="Task">SN-TASK-004812</Field><Field label="Owner">Martin Keller · Finance Platforms</Field><Field label="Due">{SCENARIO.legacyDue}</Field><Field label="Required verification">Sarah’s direct DB write and agent-mediated write on her behalf are both revoked.</Field></dl><form onSubmit={completeTask}><label className="form-label" htmlFor="completion-reference">Completion reference</label><input id="completion-reference" value={reference} onChange={e => { setReference(e.target.value); setError(''); }} placeholder="Change record or DBA confirmation reference" maxLength={160} required /><label className="form-label" htmlFor="verification-note">Verification note</label><textarea id="verification-note" value={note} onChange={e => { setNote(e.target.value); setError(''); }} placeholder="What was changed and how both access paths were verified" rows={5} maxLength={1500} required /><button type="button" className="text-link sample-evidence" onClick={() => { setReference('CHG-2026-1042 / DBA-VERIFY-0842'); setNote('Martin Keller revoked Sarah’s FIN_DB_WRITE membership and removed the Finance Operations Agent’s delegated write mapping for Sarah. Direct and agent-mediated write attempts were verified as denied.'); setError(''); }}>Use sample demo evidence<ChevronRightIcon /></button>{error && <p className="error-text" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="secondary" type="button" onClick={closeTask}>Cancel</Button><Button icon={Check} type="submit">Confirm both removals</Button></div></form></Drawer>}
  </>;
}
function ChevronRightIcon() { return <ArrowRight size={14} />; }
