import React, { useCallback, useState } from 'react';
import { ArrowRight, Bot, Check, ChevronRight, FileKey2, LockKeyhole, ShieldAlert, ShieldCheck, Users } from 'lucide-react';
import { decisions, policies, resourceName, subjectName, entitlementById, applicationById } from '../data/catalog.js';
import { effectiveDecision, fulfillmentStatus } from '../demo/state.js';
import { Avatar, Badge, Button, Drawer, Empty, Field, NextStep, Notice, PageTitle, SectionTitle, formatTime } from '../components/UI.jsx';

export default function GovernanceDecision({ state, dispatch, navigate }) {
  const [tab, setTab] = useState('human');
  const [detail, setDetail] = useState(null);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [note, setNote] = useState('Finance Manager duties reviewed. Payment access requires separate authorization and removal of conflicting Accounts Receivable Operator access.');
  const [reviewError, setReviewError] = useState('');
  const closeDetail = useCallback(() => setDetail(null), []);
  const closeReview = useCallback(() => setReviewOpen(false), []);
  const rows = decisions.filter(d => tab === 'human' ? d.scope === 'human' : d.scope === 'outbound');
  const counts = Object.fromEntries(['KEEP', 'GRANT', 'REMOVE', 'REVIEW', 'BLOCK'].map(type => [type, decisions.filter(d => d.decision === type).length]));
  if (!state.evaluated) return <><PageTitle eyebrow="POLICY EVALUATION" title="Access decisions, grounded in context." description="Evaluate Sarah’s Workday event before reviewing the target access state." /><Empty title="The role change is ready to evaluate" onAction={() => navigate(1)}>Decisions are created from the Workday business event, using the same governance model for people and agents.</Empty></>;
  function review(result) {
    if (!note.trim()) { setReviewError('Add a decision rationale before submitting.'); return; }
    dispatch({ type: 'REVIEW', result, note }); setReviewOpen(false);
  }
  return <>
    <PageTitle eyebrow="POLICY EVALUATION · WD-MOV-2026-0842" title="Access that fits the new role." description="Every permission has a decision. Every decision has a reason." action={<Button icon={ArrowRight} onClick={() => navigate(3)}>View fulfillment</Button>} />
    <div className="decision-summary">{Object.entries(counts).map(([type, count]) => <div key={type}><Badge dot={false}>{type}</Badge><strong>{count}</strong><span>{type === 'KEEP' ? 'Still appropriate' : type === 'GRANT' ? 'New role requirements' : type === 'REMOVE' ? 'No longer appropriate' : type === 'REVIEW' ? 'Human approval required' : 'Never delegated'}</span></div>)}</div>
    <div className="decision-tabs tabs" role="tablist" aria-label="Decision scope"><button role="tab" aria-selected={tab === 'human'} className={tab === 'human' ? 'active' : ''} onClick={() => setTab('human')}><Users size={17} />Human access<span>7</span></button><button role="tab" aria-selected={tab === 'agent'} className={tab === 'agent' ? 'active' : ''} onClick={() => setTab('agent')}><Bot size={17} />AI agent access<span>7</span></button></div>
    {tab === 'agent' && <section className="panel inbound-panel"><div><span className="eyebrow">INBOUND AGENT ACCESS</span><h2>Can Sarah still use the agent?</h2><div className="relationship-path"><Avatar name="Sarah Miller" /><strong>Sarah Miller</strong><ArrowRight size={18} /><Bot size={22} /><strong>Finance Operations Agent</strong></div></div><div><Badge>KEEP</Badge><p>Finance Managers remain eligible.<br />POL-AI-301 · Approved agent eligibility</p><button className="text-link" onClick={() => setDetail(decisions.find(d => d.scope === 'inbound'))}>View decision evidence<ChevronRight size={14} /></button></div></section>}
    <section className="panel decisions-panel"><SectionTitle title={tab === 'human' ? 'Human access decisions' : 'Outbound agent access decisions'} description={tab === 'human' ? 'Sarah Miller · Finance Manager target state' : 'What the Finance Operations Agent may reach on Sarah’s behalf'}><Badge tone="blue">Policy evaluated</Badge></SectionTitle><table><thead><tr><th>Entitlement / resource</th><th>Decision</th><th>Why this decision</th><th>Policy</th><th></th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className={row.decision === 'REVIEW' ? 'review-row' : row.decision === 'BLOCK' ? 'block-row' : ''}><td><div className="resource-cell"><span className="resource-icon"><FileKey2 size={17} /></span><div><button className="table-link" onClick={() => setDetail(row)}>{resourceName(row)}</button><small>{applicationById[entitlementById[row.entitlement].app].name}</small></div></div></td><td><Badge>{effectiveDecision(row, state)}</Badge></td><td className="reason-cell">{row.why}</td><td><span className="policy-id">{row.policy}</span></td><td><button className="icon-button" aria-label={`Inspect ${resourceName(row)} ${row.scope} decision`} onClick={() => setDetail(row)}><ChevronRight size={16} /></button></td></tr>)}</tbody></table></section>
    {tab === 'human' && <section className={`exception-panel ${state.review !== 'pending' ? 'resolved' : ''}`}><div className="exception-icon"><ShieldAlert size={24} strokeWidth={1.5} /></div><div className="exception-content"><span className="eyebrow">HIGH-RISK EXCEPTION · SEPARATION OF DUTIES</span><h2>{state.review === 'pending' ? 'Payment approval needs a human decision.' : state.review === 'approved' ? 'Human approval recorded. SoD still enforced.' : 'Payment approval denied. Core role access proceeds.'}</h2><p>{state.review === 'pending' ? 'SAP Payment Approval requires Patrick’s review. It cannot be activated while Accounts Receivable Operator access remains active.' : state.review === 'approved' ? 'Patrick approved the privilege with a condition: remove Accounts Receivable Operator before activation. The agent remains blocked.' : 'Sarah does not receive SAP Payment Approval. The agent remains blocked, and required manager access can still be fulfilled.'}</p><div className="exception-policies"><span>POL-RISK-204</span><span>POL-SOD-017</span><span>Reviewer: Patrick · Identity Governance</span></div></div>{state.review === 'pending' ? <Button variant="secondary" icon={ShieldCheck} onClick={() => setReviewOpen(true)}>Review exception</Button> : <Badge>{state.review === 'approved' ? 'APPROVED' : 'DENIED'}</Badge>}</section>}
    {tab === 'agent' && <Notice icon={LockKeyhole}><strong>Human permission is not agent permission.</strong> Even if Sarah’s payment approval is approved and activated, the Finance Operations Agent cannot inherit it. POL-AI-303 enforces a separate human-only boundary.</Notice>}
    <NextStep label="View fulfillment" onClick={() => navigate(3)}>The governance decision is consistent. The execution path depends on the target application.</NextStep>
    {detail && <Drawer title={resourceName(detail)} subtitle={`${detail.scope.toUpperCase()} ACCESS · DECISION DETAIL`} onClose={closeDetail}><dl><Field label="Who / subject">{subjectName(detail)}</Field><Field label="What / resource">{resourceName(detail)}</Field><Field label="Business context">Finance Analyst → Finance Manager</Field><Field label="Decision"><Badge>{effectiveDecision(detail, state)}</Badge></Field><Field label="Why">{detail.id === 'h-payment' && state.review !== 'pending' ? state.reviewNote : detail.why}</Field><Field label="Policy">{detail.policy} · {policies.find(p => p.id === detail.policy).name}</Field>{detail.id === 'h-payment' && <Field label="Additional control">POL-SOD-017 · Receivables / payment separation</Field>}<Field label="Decision timestamp">{formatTime(state.decisionEvidence.filter(e => e.rowId === detail.id).at(-1).timestamp)}</Field><Field label="Decision actor">{state.decisionEvidence.filter(e => e.rowId === detail.id).at(-1).actor}</Field></dl><Notice><strong>Decision evidence</strong> explains the access determination. Execution status, owner, SLA and completion references belong to separate fulfillment evidence.</Notice><div className="detail-status"><span>Current fulfillment status</span><Badge>{fulfillmentStatus(detail, state)}</Badge></div><Button variant="secondary" icon={ArrowRight} onClick={() => { closeDetail(); navigate(4); }}>Open evidence trail</Button></Drawer>}
    {reviewOpen && <Drawer title="Review SAP Payment Approval" subtitle="HUMAN APPROVAL · HIGH-RISK ACCESS" onClose={closeReview}><Notice tone="amber" icon={ShieldAlert}>Accounts Receivable Operator conflicts with SAP Payment Approval. An approval remains conditional until the conflicting access is removed.</Notice><dl><Field label="Requester">Sarah Miller · Finance Manager</Field><Field label="Reviewer">Patrick · Head of Identity Governance</Field><Field label="Risk">High · Payment authorization</Field><Field label="Policies">POL-RISK-204 + POL-SOD-017</Field></dl><label className="form-label" htmlFor="review-note">Decision rationale</label><textarea id="review-note" value={note} onChange={e => { setNote(e.target.value); setReviewError(''); }} rows={5} maxLength={3000} /><p className="form-hint">This rationale is stored in decision evidence. It does not grant the agent any payment permission.</p>{reviewError && <p role="alert" className="error-text">{reviewError}</p>}<div className="dialog-actions"><Button variant="danger" onClick={() => review('rejected')}>Deny request</Button><Button icon={Check} onClick={() => review('approved')}>Approve with SoD condition</Button></div></Drawer>}
  </>;
}
