import React, { useCallback, useMemo, useState } from 'react';
import { ArrowRight, Bot, Building2, CalendarDays, ChevronRight, ExternalLink, FileKey2, MapPin, Search, ShieldCheck, Users } from 'lucide-react';
import { applications, agents, entitlements, entitlementById, applicationById, identities, movers, resourceName } from '../data/catalog.js';
import { humanAccess, agentAccess, readiness, controlComplete } from '../demo/state.js';
import { Avatar, Badge, Button, Drawer, Field, NextStep, Notice, PageTitle, SectionTitle, Stat, TextLink } from '../components/UI.jsx';

export default function IdentityOverview({ state, navigate }) {
  const [tab, setTab] = useState('Identities');
  const [query, setQuery] = useState('');
  const [department, setDepartment] = useState('All departments');
  const [detail, setDetail] = useState(null);
  const close = useCallback(() => setDetail(null), []);
  const access = humanAccess(state);
  const delegated = agentAccess(state);
  const sarah = identities[0];
  const datasets = { Identities: identities, Applications: applications, 'AI agents': agents, Movers: movers };
  const filtered = useMemo(() => datasets[tab].filter(item => {
    const person = tab === 'Movers' ? identities.find(i => i.id === item.identity) : null;
    const text = [item.name, item.department, item.role, item.category, item.owner, item.from, item.to, person?.name].filter(Boolean).join(' ').toLowerCase();
    return text.includes(query.toLowerCase()) && (tab !== 'Identities' || department === 'All departments' || item.department === department);
  }), [tab, query, department]);
  return <>
    <PageTitle eyebrow="IDENTITY INTELLIGENCE" title="Access starts with context." description="One view of the person, their business role, and the agents acting on their behalf." action={<Button icon={ArrowRight} onClick={() => navigate(1)}>View role change</Button>} />
    <div className="stats-row four"><Stat label="Enterprise workforce" value="35,000" detail="Europe & North America" icon={Users} /><Stat label="Upcoming role changes" value="2,500" detail="Expected over the next 6 months" icon={CalendarDays} /><Stat label="Mover readiness baseline" value="72%" detail="Customer baseline · target 95%+" icon={ShieldCheck} /><Stat label="Governed AI agents" value="4" detail="In this synthetic demo cohort" icon={Bot} /></div>
    <div className="section-divider"><span className="eyebrow">FEATURED IDENTITY</span><span>Workday source of truth</span></div>
    <div className="profile-grid">
      <section className="panel profile-panel"><div className="profile-heading"><Avatar name="Sarah Miller" large /><div><h2>Sarah Miller</h2><span>{sarah.employeeId}</span></div><Badge>Active</Badge></div><div className="profile-role"><span>CURRENT BUSINESS ROLE</span><strong>{state.fulfillmentStarted ? 'Finance Manager' : 'Finance Analyst'}</strong><small>{state.fulfillmentStarted ? 'Effective Monday, 12 October' : 'Role change effective Monday, 12 October'}</small></div><dl className="profile-details"><Field label="Department">Finance</Field><Field label="Manager">Rachel Morgan</Field><Field label="Location">London, UK</Field><Field label="HR source">Workday <span className="connected-dot" /></Field></dl><button className="profile-event" onClick={() => navigate(1)}><CalendarDays size={19} /><div><strong>{state.fulfillmentStarted ? 'Role change is effective' : 'Upcoming role change'}</strong><small>Finance Analyst → Finance Manager</small></div><ChevronRight size={16} /></button></section>
      <section className="panel access-panel"><SectionTitle title="Direct application access" description="Actual access in the current demo state"><Badge tone="neutral">{access.length} entitlements</Badge></SectionTitle><table><thead><tr><th>Entitlement</th><th>Application</th><th>Risk</th></tr></thead><tbody>{access.map(row => <tr key={row.id}><td><span className="resource-icon"><FileKey2 size={16} /></span><strong>{resourceName(row)}</strong></td><td>{applicationById[entitlementById[row.entitlement].app].name}</td><td><Badge tone={entitlementById[row.entitlement].risk === 'High' ? 'amber' : 'neutral'}>{entitlementById[row.entitlement].risk}</Badge></td></tr>)}</tbody></table><div className="access-bottom"><ShieldCheck size={16} /><span>{state.fulfillmentStarted ? controlComplete(state) ? 'Obsolete direct and delegated access has been removed.' : 'Role access is ready; the legacy revocation is still open.' : 'Access will be re-evaluated against the new business role.'}</span></div></section>
    </div>
    <section className="panel agent-relationship"><div className="agent-intro"><span className="agent-icon"><Bot size={24} strokeWidth={1.5} /></span><div><span className="eyebrow">DELEGATED ACCESS</span><h2>Finance Operations Agent</h2><p>Govern the tool Sarah uses—and what it can do on her behalf.</p></div><Badge tone="blue">Approved AI tool</Badge></div><div className="relationship-grid"><div className="relationship-lane"><div className="lane-label"><span className="lane-number">01</span> INBOUND · WHO MAY USE THE AGENT</div><div className="relationship-path"><Avatar name="Sarah Miller" /><strong>Sarah Miller</strong><ArrowRight size={18} /><Bot size={22} /><strong>Finance Operations Agent</strong></div><small>Eligible as a Finance Analyst and Finance Manager.</small></div><div className="relationship-lane"><div className="lane-label"><span className="lane-number">02</span> OUTBOUND · WHAT THE AGENT MAY REACH</div><div className="resource-pills">{delegated.map(row => <span key={row.id}>{resourceName(row)}</span>)}</div><small>Delegated permissions are scoped to Sarah’s business context.</small></div></div></section>
    <section className="directory-section"><SectionTitle title="The Meridian workspace" description="A representative demo cohort within a global enterprise"><span className="muted-label">48 identities · 12 applications · 40 entitlements</span></SectionTitle><div className="directory-toolbar"><div className="tabs" role="tablist" aria-label="Workspace directory">{Object.keys(datasets).map(name => <button role="tab" aria-selected={tab === name} key={name} className={tab === name ? 'active' : ''} onClick={() => { setTab(name); setQuery(''); }}>{name}<span>{datasets[name].length}</span></button>)}</div><div className="filters"><label className="search-input"><Search size={16} /><input aria-label={`Search ${tab.toLowerCase()}`} placeholder={`Search ${tab.toLowerCase()}…`} value={query} onChange={e => setQuery(e.target.value)} /></label>{tab === 'Identities' && <select aria-label="Filter by department" value={department} onChange={e => setDepartment(e.target.value)}>{['All departments', 'Finance', 'HR', 'IT', 'Sales', 'Operations', 'Legal'].map(d => <option key={d}>{d}</option>)}</select>}</div></div><div className="panel directory-table"><table><thead><tr>{(tab === 'Identities' ? ['Identity', 'Business role', 'Department', 'Location', 'Status', ''] : tab === 'Applications' ? ['Application', 'Category', 'Owner', 'Fulfillment', 'Criticality', ''] : tab === 'AI agents' ? ['Agent', 'Business owner', 'Purpose', 'Autonomy', ''] : ['Identity', 'Role change', 'Effective date', 'Status', '']).map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{filtered.map(item => <tr key={item.id}>
      {tab === 'Identities' && <><td><div className="person-cell"><Avatar name={item.name} /><div><button className="table-link" onClick={() => setDetail({ type: tab, item })}>{item.name}</button><small>{item.employeeId}</small></div></div></td><td>{item.id === 'sarah' && state.fulfillmentStarted ? 'Finance Manager' : item.role}</td><td>{item.department}</td><td>{item.location}</td><td><Badge>{item.status}</Badge></td></>}
      {tab === 'Applications' && <><td><button className="table-link" onClick={() => setDetail({ type: tab, item })}>{item.name}</button></td><td>{item.category}</td><td>{item.owner}</td><td><Badge tone={item.mode === 'API' ? 'blue' : 'amber'}>{item.mode}</Badge></td><td>{item.criticality}</td></>}
      {tab === 'AI agents' && <><td><button className="table-link" onClick={() => setDetail({ type: tab, item })}>{item.name}</button></td><td>{item.owner}</td><td>{item.purpose}</td><td><Badge tone="blue">{item.autonomy}</Badge></td></>}
      {tab === 'Movers' && <><td><button className="table-link" onClick={() => item.identity === 'sarah' ? navigate(1) : setDetail({ type: tab, item })}>{identities.find(i => i.id === item.identity).name}</button></td><td>{item.from} <ArrowRight size={12} className="inline-icon" /> {item.to}</td><td>{item.effective}</td><td><Badge>{item.identity === 'sarah' ? state.fulfillmentStarted ? controlComplete(state) ? 'Complete' : 'Task open' : state.evaluated ? 'In review' : 'Ready to evaluate' : item.status}</Badge></td></>}
      <td><button className="icon-button" aria-label={`View ${item.name || item.id}`} onClick={() => setDetail({ type: tab, item })}><ChevronRight size={16} /></button></td>
    </tr>)}</tbody></table>{!filtered.length && <div className="table-empty">No matching records. Try a different search or department.</div>}<div className="table-footer"><span>Showing {filtered.length} of {datasets[tab].length} records</span><span>Synthetic enterprise data</span></div></div></section>
    <NextStep label="View role change" onClick={() => navigate(1)}>A Workday event changes Sarah’s business context. What should change with it?</NextStep>
    {detail && <Drawer title={detail.item.name || identities.find(i => i.id === detail.item.identity).name} subtitle={detail.type.toUpperCase()} onClose={close}>
      {detail.type === 'Identities' && <><dl><Field label="Employee ID">{detail.item.employeeId}</Field><Field label="Business role">{detail.item.id === 'sarah' && state.fulfillmentStarted ? 'Finance Manager' : detail.item.role}</Field><Field label="Department">{detail.item.department}</Field><Field label="Manager">{detail.item.manager}</Field><Field label="Location">{detail.item.location}</Field><Field label="Source">Workday</Field></dl><h3>Current entitlements</h3><ul className="detail-list">{(detail.item.id === 'sarah' ? access.map(row => row.entitlement) : detail.item.access).map(id => <li key={id}><FileKey2 size={16} />{entitlementById[id].name}</li>)}</ul>{detail.item.id === 'sarah' && <Button icon={ArrowRight} onClick={() => { close(); navigate(1); }}>Open Sarah’s role change</Button>}</>}
      {detail.type === 'Applications' && <><dl><Field label="Business owner">{detail.item.owner}</Field><Field label="Fulfillment pattern">{detail.item.mode}</Field><Field label="Criticality">{detail.item.criticality}</Field></dl><h3>Governed entitlements</h3><ul className="detail-list">{entitlements.filter(e => e.app === detail.item.id).map(e => <li key={e.id}><FileKey2 size={16} />{e.name}<Badge tone={e.risk === 'High' ? 'amber' : 'neutral'}>{e.risk}</Badge></li>)}</ul><Notice>The governance decision uses the same policy model across API-connected and legacy applications.</Notice></>}
      {detail.type === 'AI agents' && <><dl><Field label="Business owner">{detail.item.owner}</Field><Field label="Purpose">{detail.item.purpose}</Field><Field label="Eligible departments">{detail.item.departments.join(', ')}</Field><Field label="Operating mode">{detail.item.autonomy}</Field></dl><h3>{detail.item.id === 'finance-agent' ? 'Reachable on Sarah’s behalf' : 'Governed resources'}</h3><ul className="detail-list">{(detail.item.id === 'finance-agent' ? delegated.map(d => d.entitlement) : detail.item.resources).map(id => <li key={id}><FileKey2 size={16} />{entitlementById[id].name}</li>)}</ul><Notice>Agent access is evaluated separately from human access. Payment approval is never delegated to the Finance Operations Agent.</Notice></>}
      {detail.type === 'Movers' && <><dl><Field label="Event ID">{detail.item.id}</Field><Field label="Source">Workday</Field><Field label="Current role">{detail.item.from}</Field><Field label="Target role">{detail.item.to}</Field><Field label="Effective date">{detail.item.effective}</Field><Field label="Status"><Badge>{detail.item.status}</Badge></Field></dl><Notice>{detail.item.identity === 'sarah' ? 'Sarah’s event is the interactive scenario.' : 'This additional mover is a read-only example. Sarah’s event is the interactive scenario.'}</Notice>{detail.item.identity === 'sarah' && <Button onClick={() => { close(); navigate(1); }}>Open event</Button>}</>}
    </Drawer>}
  </>;
}
