import React, { useCallback, useMemo, useState } from 'react';
import { ArrowRight, Bot, CalendarDays, ChevronRight, FileKey2, Search, ShieldCheck, Users } from 'lucide-react';
import { applications, agents, entitlements, entitlementById, applicationById, identities, resourceName } from '../data/catalog.js';
import { ApplicationName } from '../components/ApplicationIcon.jsx';
import { SCENARIO } from '../data/scenario.js';
import { humanAccess, agentAccess, canApplyDecisions, controlComplete } from '../demo/state.js';
import { Avatar, Badge, Button, Drawer, Field, Notice, PageTitle, SectionTitle, Stat } from '../components/UI.jsx';

export default function IdentityOverview({ state, navigate }) {
  const [tab, setTab] = useState('Identities');
  const [query, setQuery] = useState('');
  const [department, setDepartment] = useState('All departments');
  const [detail, setDetail] = useState(null);
  const close = useCallback(() => setDetail(null), []);
  const access = humanAccess(state);
  const permissions = agentAccess(state);
  const agentUsageRemoved = state.tasks['a-inbound']?.status === 'Removed';
  const sarah = identities[0];
  const needsDecision = !state.applied && !canApplyDecisions(state);
  const datasets = { Identities: identities, Applications: applications, 'AI agents': agents };
  const filtered = useMemo(() => datasets[tab].filter(item => {
    const text = [item.name, item.department, item.role, item.category, item.owner].filter(Boolean).join(' ').toLowerCase();
    return text.includes(query.toLowerCase()) && (tab !== 'Identities' || department === 'All departments' || item.department === department);
  }), [tab, query, department, state]);
  return <>
    <PageTitle eyebrow="IDENTITY RECORDS" title="Overview" description="Identity records, current access and AI agent permissions for Meridian Global." action={<Button variant="secondary" icon={ArrowRight} onClick={() => navigate(1)}>View lifecycle events</Button>} />
    <section className="attention-card"><div><span className="eyebrow">NEEDS YOUR ATTENTION</span><h2>{needsDecision ? '1 mover event needs your decision' : 'Mover decisions recorded'}</h2><p>Sarah Miller · Finance Analyst → Finance Manager</p></div><Button icon={ArrowRight} onClick={() => navigate(1)}>{needsDecision ? 'Review' : 'View event'}</Button></section>
    <div className="stats-row four"><Stat label="Enterprise workforce" value="35,000" detail="Europe & North America" icon={Users} /><Stat label="Upcoming movers" value="2,500" detail="Expected over the next 6 months" icon={CalendarDays} /><Stat label="Movers provisioned by effective date" value="72%" detail="Target 95%+" icon={ShieldCheck} /><Stat label="AI agents" value="4" detail="Active" icon={Bot} /></div>
    <div className="section-divider"><span className="eyebrow">FEATURED IDENTITY</span><span>Workday source of truth</span></div>
    <div className="profile-grid">
      <section className="panel profile-panel"><div className="profile-heading"><Avatar name="Sarah Miller" large /><div><h2>Sarah Miller</h2><span>{sarah.employeeId}</span></div><Badge>Active</Badge></div><div className="profile-role"><span>CURRENT BUSINESS ROLE</span><strong>{state.fulfillmentStarted ? 'Finance Manager' : 'Finance Analyst'}</strong><small>{state.fulfillmentStarted ? `Effective ${SCENARIO.effectiveDate}` : `Mover effective ${SCENARIO.effectiveDate}`}</small></div><dl className="profile-details"><Field label="Department">Finance</Field><Field label="Manager">Rachel Morgan</Field><Field label="Location">London, UK</Field><Field label="HR source">Workday <span className="connected-dot" /></Field></dl><button className="profile-event" onClick={() => navigate('sarah')}><CalendarDays size={19} /><div><strong>{state.fulfillmentStarted ? 'Mover is effective' : 'Upcoming mover'}</strong><small>Finance Analyst → Finance Manager</small></div><ChevronRight size={16} /></button></section>
      <section className="panel access-panel"><SectionTitle title="Current access" description="Assigned application entitlements"><Badge tone="neutral">{access.length} entitlements</Badge></SectionTitle><table><thead><tr><th>Entitlement</th><th>Application</th><th>Risk</th></tr></thead><tbody>{access.map(row => <tr key={row.id}><td><span className="resource-icon"><FileKey2 size={16} /></span><strong>{resourceName(row)}</strong></td><td><ApplicationName appId={entitlementById[row.entitlement].app} /></td><td><Badge tone={entitlementById[row.entitlement].risk === 'High' ? 'amber' : 'neutral'}>{entitlementById[row.entitlement].risk}</Badge></td></tr>)}</tbody></table><div className="access-bottom"><ShieldCheck size={16} /><span>{state.fulfillmentStarted ? controlComplete(state) ? 'Applied access decisions are provisioned.' : 'Role access provisioned. 1 manual task open.' : state.applied ? 'Changes scheduled for the effective date.' : 'Access review scheduled for the lifecycle event.'}</span></div></section>
    </div>
    <section className="panel agent-relationship"><div className="agent-intro"><span className="agent-icon"><Bot size={24} strokeWidth={1.5} /></span><div><span className="eyebrow">AI agent · Owner: Sarah Miller</span><h2>Finance Operations Agent</h2><p>Agent identity with role-based usage and application permissions.</p></div><Badge tone="blue">Approved AI tool</Badge></div><div className="relationship-grid"><div className="relationship-lane"><div className="lane-label"><span className="lane-number">01</span> Agent usage · Who may use the agent</div><div className="relationship-path"><Avatar name="Sarah Miller" /><strong>Sarah Miller</strong><ArrowRight size={18} /><Bot size={22} /><strong>Finance Operations Agent</strong></div><small>{agentUsageRemoved ? 'Agent usage removed for Sarah Miller.' : 'Eligible as a Finance Analyst and Finance Manager.'}</small></div><div className="relationship-lane"><div className="lane-label"><span className="lane-number">02</span> Agent permissions · What the agent may access</div><div className="resource-pills">{permissions.map(row => <span key={row.id}>{resourceName(row)}</span>)}</div><small>Application permissions assigned to the Finance Operations Agent.</small></div></div></section>
    <section className="directory-section"><SectionTitle title="Directory" description="Identities, applications and AI agents"><span className="muted-label">48 identities · 12 applications · 40 entitlements</span></SectionTitle><div className="directory-toolbar"><div className="tabs" role="tablist" aria-label="Workspace directory">{Object.keys(datasets).map(name => <button role="tab" aria-selected={tab === name} key={name} className={tab === name ? 'active' : ''} onClick={() => { setTab(name); setQuery(''); }}>{name}<span>{datasets[name].length}</span></button>)}</div><div className="filters"><label className="search-input"><Search size={16} /><input aria-label={`Search ${tab.toLowerCase()}`} placeholder={`Search ${tab.toLowerCase()}…`} value={query} onChange={e => setQuery(e.target.value)} /></label>{tab === 'Identities' && <select aria-label="Filter by department" value={department} onChange={e => setDepartment(e.target.value)}>{['All departments', 'Finance', 'HR', 'IT', 'Sales', 'Operations', 'Legal'].map(d => <option key={d}>{d}</option>)}</select>}</div></div><div className="panel directory-table"><table><thead><tr>{(tab === 'Identities' ? ['Identity', 'Business role', 'Department', 'Location', 'Status', ''] : tab === 'Applications' ? ['Application', 'Category', 'Owner', 'Provisioning', 'Criticality', ''] : ['Agent identity', 'Owner', 'Purpose', 'Operating mode', '']).map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{filtered.map(item => <tr key={item.id}>
      {tab === 'Identities' && <><td><div className="person-cell"><Avatar name={item.name} /><div><button className="table-link" onClick={() => setDetail({ type: tab, item })}>{item.name}</button><small>{item.employeeId}</small></div></div></td><td>{item.id === 'sarah' && state.fulfillmentStarted ? 'Finance Manager' : item.role}</td><td>{item.department}</td><td>{item.location}</td><td><Badge>{item.status}</Badge></td></>}
      {tab === 'Applications' && <><td><button className="table-link" onClick={() => setDetail({ type: tab, item })}><ApplicationName appId={item.id} /></button></td><td>{item.category}</td><td>{item.owner}</td><td><Badge tone={item.mode === 'API' ? 'blue' : 'amber'}>{item.mode}</Badge></td><td>{item.criticality}</td></>}
      {tab === 'AI agents' && <><td><button className="table-link" onClick={() => setDetail({ type: tab, item })}>{item.name}</button></td><td><span className="person-cell"><Avatar name={item.owner} />{item.owner}</span></td><td>{item.purpose}</td><td><Badge tone="blue">{item.autonomy}</Badge></td></>}
      <td><button className="icon-button" aria-label={`View ${item.name || item.id}`} onClick={() => setDetail({ type: tab, item })}><ChevronRight size={16} /></button></td>
    </tr>)}</tbody></table>{!filtered.length && <div className="table-empty">No matching records. Try a different search or department.</div>}<div className="table-footer"><span>Showing {filtered.length} of {datasets[tab].length} records</span><span>Meridian Global</span></div></div></section>
    {detail && <Drawer title={detail.item.name} subtitle={detail.type.toUpperCase()} onClose={close}>
      {detail.type === 'Identities' && <><Avatar name={detail.item.name} large /><dl><Field label="Employee ID">{detail.item.employeeId}</Field><Field label="Business role">{detail.item.id === 'sarah' && state.fulfillmentStarted ? 'Finance Manager' : detail.item.role}</Field><Field label="Department">{detail.item.department}</Field><Field label="Manager">{detail.item.manager}</Field><Field label="Location">{detail.item.location}</Field><Field label="Source">Workday</Field></dl><h3>Current entitlements</h3><ul className="detail-list">{(detail.item.id === 'sarah' ? access.map(row => row.entitlement) : detail.item.access).map(id => <li key={id}><ApplicationName appId={entitlementById[id].app} indicator={false} />{entitlementById[id].name}</li>)}</ul>{detail.item.id === 'sarah' && <Button icon={ArrowRight} onClick={() => { close(); navigate('sarah'); }}>Open lifecycle event</Button>}</>}
      {detail.type === 'Applications' && <><div className="drawer-application"><ApplicationName appId={detail.item.id} /></div><dl><Field label="Owner">{detail.item.owner}</Field><Field label="Provisioning method">{detail.item.mode}</Field><Field label="Criticality">{detail.item.criticality}</Field></dl><h3>Governed entitlements</h3><ul className="detail-list">{entitlements.filter(e => e.app === detail.item.id).map(e => <li key={e.id}><FileKey2 size={16} />{e.name}<Badge tone={e.risk === 'High' ? 'amber' : 'neutral'}>{e.risk}</Badge></li>)}</ul><Notice>Provisioning method: {detail.item.mode === 'API' ? 'automated connector' : 'manual task'}</Notice></>}
      {detail.type === 'AI agents' && <><dl><Field label="Owner">{detail.item.owner}</Field><Field label="Purpose">{detail.item.purpose}</Field><Field label="Eligible departments">{detail.item.departments.join(', ')}</Field><Field label="Operating mode">{detail.item.autonomy}</Field></dl><h3>{detail.item.id === 'finance-agent' ? 'Agent permissions' : 'Governed resources'}</h3><ul className="detail-list">{(detail.item.id === 'finance-agent' ? permissions.map(d => d.entitlement) : detail.item.resources).map(id => <li key={id}><ApplicationName appId={entitlementById[id].app} indicator={false} />{entitlementById[id].name}</li>)}</ul><Notice>Agent access is evaluated separately from human access. Payment approval is restricted to human identities (POL-AI-303).</Notice></>}
    </Drawer>}
  </>;
}
