import React from 'react';
import { ArrowRight, Bot, CalendarDays, Check, GitBranch, ShieldCheck, Workflow } from 'lucide-react';
import { Badge, Button, Field, NextStep, Notice, PageTitle, SectionTitle } from '../components/UI.jsx';

export default function RoleChangeEvent({ state, dispatch, navigate }) {
  return <>
    <PageTitle eyebrow="WORKFORCE CHANGE" title="One business event. A new access context." description="Workday provides the change. Northstar evaluates what it means across people, agents, and applications." action={state.evaluated ? <Button icon={ArrowRight} onClick={() => navigate(2)}>View governance decisions</Button> : <Button icon={ShieldCheck} onClick={() => { dispatch({ type: 'EVALUATE' }); navigate(2); }}>Evaluate access</Button>} />
    <section className="panel event-panel"><div className="event-header"><div className="event-source"><span className="workday-logo">w<span /></span><div><strong>Workday role change</strong><small>WD-MOV-2026-0842 · HR source of truth</small></div></div><Badge tone={state.evaluated ? 'green' : 'blue'}>{state.evaluated ? 'Evaluated' : 'Received'}</Badge></div><div className="event-body"><div className="event-person"><span className="avatar large">SM</span><div><h2>Sarah Miller</h2><span>MG-010482 · Finance · London, UK</span></div></div><div className="role-transition"><div><span className="eyebrow">PREVIOUS ROLE</span><h3>Finance Analyst</h3><p>Operational Finance access</p></div><span className="transition-arrow"><ArrowRight size={26} /></span><div className="target-role"><span className="eyebrow">NEW ROLE</span><h3>Finance Manager</h3><p>Management and budget accountability</p></div></div><div className="event-metadata"><div><CalendarDays size={17} /><span>Effective <strong>Monday, 12 October 2026</strong></span></div><div><GitBranch size={17} /><span>Source event received <strong>Friday, 9 October · 09:00 UTC</strong></span></div></div></div></section>
    <div className="event-context-grid"><section><SectionTitle title="What needs to be re-evaluated" description="The change is broader than adding a new role." /><div className="evaluation-list"><div><span className="evaluation-icon"><ShieldCheck size={21} /></span><div><h3>Sarah’s direct access</h3><p>Keep what still fits. Grant what she needs. Remove obsolete privileges.</p></div><span className="evaluation-number">01</span></div><div><span className="evaluation-icon"><Workflow size={21} /></span><div><h3>High-risk permissions</h3><p>Route payment approval for review and enforce separation of duties.</p></div><span className="evaluation-number">02</span></div><div><span className="evaluation-icon"><Bot size={21} /></span><div><h3>The agent acting on her behalf</h3><p>Evaluate both eligibility to use the agent and its delegated permissions.</p></div><span className="evaluation-number">03</span></div></div></section><aside className="business-context"><span className="eyebrow">WHY THIS MATTERS TO MERIDIAN</span><h2>Change is accelerating.<br />Control must keep pace.</h2><p>Meridian’s existing governance has delivered value. Custom workflows, specialist integrations and manual exceptions now make consistent proof harder.</p><div className="context-finding"><span>RECENT AUDIT FINDING</span><strong>Residual Finance access after internal role changes.</strong></div><div className="context-finding"><span>WORKFORCE TRANSFORMATION</span><strong>2,500 movers expected over six months.</strong></div></aside></div>
    <Notice>Evaluation prepares decisions on Friday. The effective-date fulfillment simulation advances the scenario to Monday; it does not execute changes in a real system.</Notice>
    <NextStep label={state.evaluated ? 'View decisions' : 'Evaluate access'} onClick={() => { if (!state.evaluated) dispatch({ type: 'EVALUATE' }); navigate(2); }}>What should Sarah keep, gain, lose—and what should never pass to her agent?</NextStep>
  </>;
}
